# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 12:22
from __future__ import unicode_literals

from django.db import migrations, models

import captcha.helper


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphCaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha',
                 models.CharField(blank=True, default=captcha.helper.gen_graph_captcha, max_length=6, null=True,
                                  verbose_name='图形验证码')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinkCaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                'expired_at', models.DateTimeField(default=captcha.helper.link_captcha_expire_at, verbose_name='过期时间')),
                ('captcha',
                 models.CharField(blank=True, default=captcha.helper.gen_link_captcha, max_length=32, null=True,
                                  verbose_name='链接验证码')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
