# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='链接')),
                ('count', models.IntegerField(default=0, verbose_name='点击量')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
            ],
        ),
    ]
