# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 15:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import oauth.generators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='应用名')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('client_id', models.CharField(default=oauth.generators.generate_client_id, max_length=255, unique=True,
                                               verbose_name='客户端ID')),
                ('client_secret', models.CharField(default=oauth.generators.generate_client_secret, max_length=255,
                                                   verbose_name='客户端密钥')),
                ('site_uri', models.URLField(blank=True, max_length=255, null=True, verbose_name='主站地址')),
                ('redirect_uri', models.URLField(max_length=255, verbose_name='回调地址')),
                ('grant_type',
                 models.CharField(choices=[('authorization_code', '授权码'), ('jwt_bearer', 'JWT TOKEN')], max_length=32,
                                  verbose_name='授权类型')),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_at',
                 models.DateTimeField(default=oauth.generators.grant_expire_at_time, verbose_name='token失效时间')),
                ('code', models.CharField(db_index=True, default=oauth.generators.generate_grant_code, max_length=255,
                                          unique=True, verbose_name='授权码')),
                ('scope', models.TextField(choices=[('read', '读'), ('read write', '读写')], default='read', max_length=32,
                                           verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_at',
                 models.DateTimeField(default=oauth.generators.token_expire_at_time, verbose_name='token失效时间')),
                ('access_token', models.CharField(max_length=1024, verbose_name='access_token')),
                ('refresh_token', models.CharField(max_length=1024, verbose_name='refresh_token')),
                ('scope',
                 models.TextField(choices=[('read', '读'), ('read write', '读写')], default='read', max_length=32)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.Application',
                                                  verbose_name='应用')),
            ],
        ),
    ]
