# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='目录名')),
                ('type', models.IntegerField(choices=[(1, '文章'), (2, '照片')])),
            ],
        ),
    ]
