# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='type',
            field=models.IntegerField(choices=[(1, '文章'), (2, '照片'), (3, '闲扯')]),
        ),
    ]
