# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-21 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_to', models.IntegerField(verbose_name='评论对象id')),
                ('type', models.IntegerField(choices=[(1, '文章'), (2, '照片'), (3, '闲扯')], verbose_name='评论类别')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
